version: '3.4'

services:
  arz.eda:
    image: ${DOCKER_REGISTRY-}arzeda
    build:
      context: .
      dockerfile: arz.eda/Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - "postgres_image"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=arzeda;username=jozh_admin;password=jozhvilis777"
  postgres_image:
    image: postgres:latest
    ports:
      - "55432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "jozh_admin"
      POSTGRES_PASSWORD: "jozhvilis777"
volumes:
  db_volume: