version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - "arz.eda"
      - "arzeda.front"
      - "arzeda.admin"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=arz.eda
      - NGINX_PORT=80
  arz.eda:
    image: ${DOCKER_REGISTRY-}arzeda
    build:
      context: .
      dockerfile: arz.eda/Dockerfile
    ports:
      - "50000:80"
    depends_on:
      - "postgres_image"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=arzeda;username=jozh_admin;password=jozhvilis777"
  postgres_image:
    image: postgres:latest
    ports:
      - "55432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "jozh_admin"
      POSTGRES_PASSWORD: "jozhvilis777"
      POSTGRES_DB: "arzeda"
  arzeda.front:
    image: ${DOCKER_REGISTRY-}arzeda.front
    build:
      context: ../arzeda.front/
    ports:
      - "8080:8080"
    volumes:
      - "../arzeda.front:/app"
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  
  arzeda.admin:
    image: ${DOCKER_REGISTRY-}arzeda.admin
    build:
      context: ../arzeda.admin/
    ports:
      - "8082:8080"
    volumes:
      - "../arzeda.admin:/app"
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
volumes:
  db_volume: